import discord, os, random, json
from discord.ext import commands

with open('config.json') as f: 
  config = json.load(f)

token = config.get('token')
prefix = config.get('prefix')
vanis = commands.Bot(command_prefix=prefix, case_insensitive=True, self_bot=True)
vanis.remove_command("help")

@vanis.event
async def on_ready():
  print(f""" \u001b[31m
    ╔════════════════════════════════════════════╗
        ╦ ╦╦ ╦╦═╗╔═╗╦ ╦  ╔═╗╦═╗╔═╗╔═╗╔═╗╔═╗╦═╗ 
        ╚╦╝║ ║╠╦╝║ ║║ ║  ╠═╝╠╦╝║╣ ╚═╗╚═╗║╣ ╠╦╝
         ╩ ╚═╝╩╚═╚═╝╚═╝  ╩  ╩╚═╚═╝╚═╝╚═╝╚═╝╩╚═
    ╚════════════════════════════════════════════╝
    To use the presser, type "vanis" in the chat to
    activate it.
""")



@vanis.event
async def on_message(message):
    channel = message.channel
    if message.content.endswith('vanis'):

        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('U CANT PRESSURE ME')
        await message.channel.send ('1')
        await message.channel.send ('UR A SKID LOOLOOLOL')
        await message.channel.send ('DONT GET TIRED')
        await message.channel.send ('LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL')
        await message.channel.send ('LLOLOLOLOLOLOLLLOO')
        await message.channel.send ('LOOLLOLOLO')
        await message.channel.send ('LOLL')
        await message.channel.send ('YOU FUCKING SUCK LAME ASS NIGGA')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('U CANT PRESSURE ME')
        await message.channel.send ('1')
        await message.channel.send ('UR A SKID LOOLOOLOL')
        await message.channel.send ('DONT GET TIRED')
        await message.channel.send ('LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL')
        await message.channel.send ('LLOLOLOLOLOLOLLLOO')
        await message.channel.send ('LOOLLOLOLO')
        await message.channel.send ('LOLL')
        await message.channel.send ('YOU FUCKING SUCK LAME ASS NIGGA')
        await message.channel.send ('YOUR SO BAD LOOOOL')
        await message.channel.send ('LAME ASS NIGGA U CANT KEEP UP WITH ME')
        await message.channel.send ('YOUR SO BAD LOOOOL')
        await message.channel.send ('LAME ASS NIGGA U CANT KEEP UP WITH ME')
        await message.channel.send ('ASS')
        await message.channel.send ('LOOLLOLOLO')
        await message.channel.send ('LOLL')
        await message.channel.send ('YOU FUCKING SUCK LAME ASS NIGGA')
        await message.channel.send ('YOUR SO BAD LOOOOL')
        await message.channel.send ('LAME ASS NIGGA U CANT KEEP UP WITH ME')
        await message.channel.send ('ASS')
        await message.channel.send ('BITCH')
        await message.channel.send ('LOO')
        await message.channel.send ('LLOL')
        await message.channel.send ('LO')
        await message.channel.send ('COME')
        await message.channel.send ('LETS')
        await message.channel.send ('SKID RETARDED ASS NIGGA UR SO SHIT')
        await message.channel.send ('LOOOOOOOOOOOOOOOOOLLLLLLLLLOOOOOOOOOL')
        await message.channel.send ('LOOOOOOOOOOOOOOL')
        await message.channel.send ('OOOOOOOOOLOLO')
        await message.channel.send ('OLOLOLOLOLOL')
        await message.channel.send ('FOLOLLOLOLOLO')
        await message.channel.send ('ASS')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')   
        await message.channel.send ('BITCH')
        await message.channel.send ('LOO')
        await message.channel.send ('LLOL')
        await message.channel.send ('LO')
        await message.channel.send ('COME')
        await message.channel.send ('LETS')
        await message.channel.send ('SKID RETARDED ASS NIGGA UR SO SHIT')
        await message.channel.send ('LOOOOOOOOOOOOOOOOOLLLLLLLLLOOOOOOOOOL')
        await message.channel.send ('LOOOOOOOOOOOOOOL')
        await message.channel.send ('OOOOOOOOOLOLO')
        await message.channel.send ('OLOLOLOLOLOL')
        await message.channel.send ('FOLOLLOLOLOLO')
        await message.channel.send ('ASS')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('BITCH')
        await message.channel.send ('LOLO')
        await message.channel.send ('LOOL')
        await message.channel.send ('OLOL')
        await message.channel.send ('LOLO')
        await message.channel.send ('DONT STOP')
        await message.channel.send ('SPAMMING')
        await message.channel.send ('LAME ASS NIGGA UR SO ASS LOOOOOL')
        await message.channel.send ('WEAK ASS BITCH UR SO SHIT')
        await message.channel.send ('WEAK ASS NIGGA')
        await message.channel.send ('UR SO SHIT LOOOOOLL')
        await message.channel.send ('KEEP PACKING SON DONT STOP')
        await message.channel.send ('FOCUS SON DONT FOLD LOOOOL UR ASS')
        await message.channel.send ('WEAK ASS BITCH YOU CANT LAST WITH ME')
        await message.channel.send ('WHY DO YOU FEAR ME SO MUCH SON?')
        await message.channel.send ('HE CANT KEEP UP WITH ME')
        await message.channel.send ('HES MY JR LMFAOAOAOA')
        await message.channel.send ('FREAK DOESNT KNOW WHAT HE GOT HIMSELF INTO')
        await message.channel.send ('MY SON IS CRYING RN HE SLOWING DOWN')
        await message.channel.send ('HES GETTING HAND CRAMPS')
        await message.channel.send ('FOCUS UP SON FUCKING WEAK TROLL')
        await message.channel.send ('WEAK BITCH STOP DUCKING ME SON U CANT PRESS ME U SUCK')
        await message.channel.send ('LOOOL')
        await message.channel.send ('OL')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('U CANT PRESSURE ME')
        await message.channel.send ('1')
        await message.channel.send ('UR A SKID LOOLOOLOL')
        await message.channel.send ('DONT GET TIRED')
        await message.channel.send ('LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL')
        await message.channel.send ('LLOLOLOLOLOLOLLLOO')
        await message.channel.send ('LOOLLOLOLO')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('U CANT PRESSURE ME')
        await message.channel.send ('1')
        await message.channel.send ('UR A SKID LOOLOOLOL')
        await message.channel.send ('DONT GET TIRED')
        await message.channel.send ('LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL')
        await message.channel.send ('LLOLOLOLOLOLOLLLOO')
        await message.channel.send ('LOOLLOLOLO')
        await message.channel.send ('L')
        await message.channel.send ('OLO')
        await message.channel.send ('LO')
        await message.channel.send ('O')
        await message.channel.send ('LOLOLO')
        await message.channel.send ('L')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('SHUT')
        await message.channel.send ('THE')
        await message.channel.send ('FUCK')
        await message.channel.send ('UP')
        await message.channel.send ('AND')
        await message.channel.send ('COME')
        await message.channel.send ('MAKE A PRINT YOU SKIDDDDDDDDDD LOLLLLLLLLLLLLLLLL')
        await message.channel.send ('FUCKING')
        await message.channel.send ('PUSSY')
        await message.channel.send ('YOU')
        await message.channel.send ('SUCK')
        await message.channel.send ('FREAK DOESNT KNOW WHAT HE GOT HIMSELF INTO')
        await message.channel.send ('MY SON IS CRYING RN HE SLOWING DOWN')
        await message.channel.send ('HES GETTING HAND CRAMPS')
        await message.channel.send ('FOCUS UP SON FUCKING WEAK TROLL')
        await message.channel.send ('WEAK BITCH STOP DUCKING ME SON U CANT PRESS ME U SUCK')
        await message.channel.send ('LOOOL')
        await message.channel.send ('OL')
        await message.channel.send ('L')
        await message.channel.send ('OLO')
        await message.channel.send ('LO')
        await message.channel.send ('O')
        await message.channel.send ('LOLOLO')
        await message.channel.send ('L')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('SHUT')
        await message.channel.send ('THE')
        await message.channel.send ('FUCK')
        await message.channel.send ('UP')
        await message.channel.send ('AND')
        await message.channel.send ('COME')
        await message.channel.send ('MAKE A PRINT YOU SKIDDDDDDDDDD LOLLLLLLLLLLLLLLLL')
        await message.channel.send ('FUCKING')
        await message.channel.send ('PUSSY')
        await message.channel.send ('YOU')
        await message.channel.send ('SUCK')
        await message.channel.send ('FREAK DOESNT KNOW WHAT HE GOT HIMSELF INTO')
        await message.channel.send ('MY SON IS CRYING RN HE SLOWING DOWN')
        await message.channel.send ('HES GETTING HAND CRAMPS')
        await message.channel.send ('FOCUS UP SON FUCKING WEAK TROLL')
        await message.channel.send ('WEAK BITCH STOP DUCKING ME SON U CANT PRESS ME U SUCK')
        await message.channel.send ('LOOOL')
        await message.channel.send ('OL')
        await message.channel.send ('L')
        await message.channel.send ('OLO')
        await message.channel.send ('LO')
        await message.channel.send ('O')
        await message.channel.send ('LOLOLO')
        await message.channel.send ('L')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('SHUT')
        await message.channel.send ('THE')
        await message.channel.send ('FUCK')
        await message.channel.send ('UP')
        await message.channel.send ('AND')
        await message.channel.send ('COME')
        await message.channel.send ('MAKE A PRINT YOU SKIDDDDDDDDDD LOLLLLLLLLLLLLLLLL')
        await message.channel.send ('FUCKING')
        await message.channel.send ('PUSSY')
        await message.channel.send ('YOU')
        await message.channel.send ('SUCK')
        await message.channel.send ('FREAK DOESNT KNOW WHAT HE GOT HIMSELF INTO')
        await message.channel.send ('MY SON IS CRYING RN HE SLOWING DOWN')
        await message.channel.send ('HES GETTING HAND CRAMPS')
        await message.channel.send ('FOCUS UP SON FUCKING WEAK TROLL')
        await message.channel.send ('WEAK BITCH STOP DUCKING ME SON U CANT PRESS ME U SUCK')
        await message.channel.send ('LOOOL')
        await message.channel.send ('OL')
        await message.channel.send ('L')
        await message.channel.send ('OLO')
        await message.channel.send ('LO')
        await message.channel.send ('O')
        await message.channel.send ('LOLOLO')
        await message.channel.send ('L')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('SHUT')
        await message.channel.send ('THE')
        await message.channel.send ('FUCK')
        await message.channel.send ('UP')
        await message.channel.send ('AND')
        await message.channel.send ('COME')
        await message.channel.send ('MAKE A PRINT YOU SKIDDDDDDDDDD LOLLLLLLLLLLLLLLLL')
        await message.channel.send ('FUCKING')
        await message.channel.send ('PUSSY')
        await message.channel.send ('YOU')
        await message.channel.send ('SUCK')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHAT MOVING SON')
        await message.channel.send ('NO BREAKS FOR YOU KEEP ON GOING SON')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO SHOULD I GIVE MY SON A CHANCE')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('PRAY YOU WONT FOLD TONIGHT')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('LOL FUCKING RETARDED BITCH')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('U CANT PRESSURE ME')
        await message.channel.send ('1')
        await message.channel.send ('UR A SKID LOOLOOLOL')
        await message.channel.send ('DONT GET TIRED')
        await message.channel.send ('LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL')
        await message.channel.send ('LLOLOLOLOLOLOLLLOO')
        await message.channel.send ('LOOLLOLOLO')



vanis.run(token, bot=False)